### ISSUE TITLE
Confusing UI component

### ISSUE THREAD

**Issue by GregTheGreek** [element-fi/frontend-monorepo#428]
If you're already in the GSC the loader + join button should be changed to something else

<img width="520" alt="image" src="https://user-images.githubusercontent.com/16929357/209482614-c1439e35-654e-4ca9-bdb2-58633d0d141e.png">

**Comment by DannyDelott** [comment]
Thanks for this feedback. We've identified quite a few shortcomings with this first iteration and plan to sunset this UI in the near future. A new Council UI is currently in development and will ship in the next month or two. We'll make sure this is addressed in the new Voter page.
